### ISSUE TITLE
Failed to select

### ISSUE THREAD

**Issue by fire** [kuenishi/presto-riak#10]
The setup is with presto 0.98 and riak 2.0.5. The presto engine is unable to get results.

```
presto:t> select * from logs l, users u where l.accessor = u.id;
Query 20150324_080414_00015_x5a2a failed: com.ericsson.otp.erlang.OtpErlangAtom cannot be cast to com.ericsson.otp.erlang.OtpErlangList

presto:t> explain select * from logs l, users u where l.accessor = u.id;
                                                                                 Query Plan                                                    
-----------------------------------------------------------------------------------------------------------------------------------------------
 - Output[timestamp, method, status, accessor, id, name, army] => [timestamp:varchar, method:varchar, status:bigint, accessor:bigint, id:bigint
     - Exchange[GATHER] => timestamp:varchar, method:varchar, status:bigint, accessor:bigint, id:bigint, name:varchar, army:varchar            
         - InnerJoin[("accessor" = "id")] => [timestamp:varchar, method:varchar, status:bigint, accessor:bigint, id:bigint, name:varchar, army:
             - TableScan[riak:riak:t:logs, original constraint=true] => [timestamp:varchar, method:varchar, status:bigint, accessor:bigint]    
                     timestamp := riak:RiakColumnHandle{connectorId=riak, column=timestamp:varchar(index=false), ordinalPosition=2}            
                     method := riak:RiakColumnHandle{connectorId=riak, column=method:varchar(index=false), ordinalPosition=3}                  
                     status := riak:RiakColumnHandle{connectorId=riak, column=status:bigint(index=false), ordinalPosition=4}                   
                     accessor := riak:RiakColumnHandle{connectorId=riak, column=accessor:bigint(index=false), ordinalPosition=5}               
             - Exchange[REPLICATE] => id:bigint, name:varchar, army:varchar                                                                    
                 - TableScan[riak:riak:t:users, original constraint=true] => [id:bigint, name:varchar, army:varchar]                           
                         id := riak:RiakColumnHandle{connectorId=riak, column=id:bigint(index=false), ordinalPosition=2}                       
                         name := riak:RiakColumnHandle{connectorId=riak, column=name:varchar(index=false), ordinalPosition=3}                  
                         army := riak:RiakColumnHandle{connectorId=riak, column=army:varchar(index=false), ordinalPosition=4}                  
```

**Comment by kuenishi** [comment]
Did you put `ldna.beam` to `basho-patches`?

**Comment by fire** [comment]
ldnas was placed in basho-patches and now there is another problem.

```
2015-03-24T09:01:01.688-0700	 INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========
2015-03-24T09:01:02.302-0700	 INFO	Query-20150324_160102_00000_czxss-166	com.basho.riak.presto.RiakMetadata	getTableHandle;
2015-03-24T09:01:02.359-0700	ERROR	Query-20150324_160102_00000_czxss-166	com.basho.riak.presto.RiakMetadata	no tables found at jmx.logs
2015-03-24T09:01:02.382-0700	 INFO	query-execution-0	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20150324_160102_00000_czxss :: elapsed 97.00ms :: planning 0.00ms :: scheduling 97.00ms :: running 0.00ms :: finishing 97.00ms :: begin 2015-03-24T09:01:02.265-07:00 :: end 2015-03-24T09:01:02.362-07:00
2015-03-24T09:01:12.450-0700	 INFO	20150324_160111_00002_czxss.1.0-0-55	com.basho.riak.presto.RiakMetadata	listTables for default;
2015-03-24T09:01:12.463-0700	 INFO	20150324_160111_00002_czxss.1.0-0-55	com.basho.riak.presto.RiakClient	checking... default

2015-03-24T09:01:12.519-0700	 INFO	20150324_160111_00002_czxss.1.0-0-55	com.basho.riak.presto.RiakMetadata	table logs found.
2015-03-24T09:01:12.519-0700	 INFO	20150324_160111_00002_czxss.1.0-0-55	com.basho.riak.presto.RiakMetadata	table users found.
2015-03-24T09:01:12.519-0700	 INFO	20150324_160111_00002_czxss.1.0-0-55	com.basho.riak.presto.RiakMetadata	listTables for default: 2 tables found
2015-03-24T09:01:12.713-0700	 INFO	query-execution-1	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20150324_160111_00002_czxss :: elapsed 693.00ms :: planning 128.34ms :: scheduling 428.00ms :: running 112.00ms :: finishing 25.00ms :: begin 2015-03-24T09:01:11.966-07:00 :: end 2015-03-24T09:01:12.659-07:00
2015-03-24T09:01:12.747-0700	 INFO	query-execution-4	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20150324_160111_00001_czxss :: elapsed 799.00ms :: planning 156.19ms :: scheduling 343.00ms :: running 230.00ms :: finishing 70.00ms :: begin 2015-03-24T09:01:11.938-07:00 :: end 2015-03-24T09:01:12.737-07:00
2015-03-24T09:01:13.102-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableHandle;
2015-03-24T09:01:13.110-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.120-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata
2015-03-24T09:01:13.120-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata>> default.logs
2015-03-24T09:01:13.125-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.131-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.132-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableHandle;
2015-03-24T09:01:13.137-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.137-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata
2015-03-24T09:01:13.137-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata>> default.users
2015-03-24T09:01:13.142-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.147-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.166-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	==========================tupleDomain=============================
2015-03-24T09:01:13.166-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	TupleDomain:ALL
2015-03-24T09:01:13.170-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.175-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	==========================tupleDomain=============================
2015-03-24T09:01:13.175-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	TupleDomain:ALL
2015-03-24T09:01:13.179-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.189-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	==========================tupleDomain=============================
2015-03-24T09:01:13.190-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	TupleDomain:ALL
2015-03-24T09:01:13.194-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.195-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	==========================tupleDomain=============================
2015-03-24T09:01:13.195-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakSplitManager	TupleDomain:ALL
2015-03-24T09:01:13.199-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.208-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.209-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.209-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.209-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.209-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata
2015-03-24T09:01:13.209-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata>> default.logs
2015-03-24T09:01:13.214-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.214-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.215-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.215-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getColumnMetadata
2015-03-24T09:01:13.215-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata
2015-03-24T09:01:13.215-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakMetadata	getTableMetadata>> default.users
2015-03-24T09:01:13.218-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.224-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.logs)
2015-03-24T09:01:13.242-0700	 INFO	Query-20150324_160113_00003_czxss-165	com.basho.riak.presto.RiakClient	RiakClient.getTable(default.users)
2015-03-24T09:01:13.265-0700	ERROR	Stage-20150324_160113_00003_czxss.1-173	com.facebook.presto.execution.SqlStageExecution	Error while starting stage 20150324_160113_00003_czxss.1
com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.util.Failures.checkCondition(Failures.java:80) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.NodeScheduler$NodeSelector.computeAssignments(NodeScheduler.java:231) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.SqlStageExecution.scheduleSourcePartitionedNodes(SqlStageExecution.java:640) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.SqlStageExecution.startTasks(SqlStageExecution.java:555) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.SqlStageExecution$$Lambda$228/851417037.run(Unknown Source) [presto-main-0.98.jar:0.98]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
2015-03-24T09:01:13.265-0700	ERROR	Stage-20150324_160113_00003_czxss.2-171	com.facebook.presto.execution.SqlStageExecution	Error while starting stage 20150324_160113_00003_czxss.2
com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.util.Failures.checkCondition(Failures.java:80) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.NodeScheduler$NodeSelector.computeAssignments(NodeScheduler.java:231) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.SqlStageExecution.scheduleSourcePartitionedNodes(SqlStageExecution.java:640) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.SqlStageExecution.startTasks(SqlStageExecution.java:555) ~[presto-main-0.98.jar:0.98]
	at com.facebook.presto.execution.SqlStageExecution$$Lambda$228/851417037.run(Unknown Source) [presto-main-0.98.jar:0.98]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
2015-03-24T09:01:13.288-0700	 INFO	query-execution-7	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20150324_160113_00003_czxss :: elapsed 157.00ms :: planning 151.97ms :: scheduling 5.00ms :: running 0.00ms :: finishing 5.00ms :: begin 2015-03-24T09:01:13.098-07:00 :: end 2015-03-24T09:01:13.255-07:00
```

**Comment by fire** [comment]
The system now runs via rp repository, but can you write instructions on how to create a table schema using your tool and insert values into the table?

**Comment by fire** [comment]
Instructions that work are:

```
./bin/presto-riak-ctl localhost 8087 setup-schema t
./bin/presto-riak-ctl localhost 8087 create-tabledef t users.json 
./bin/presto-riak-ctl localhost 8087 create-tabledef t logs.json 
./bin/testdata.py
./bin/presto-cli --server localhost:8080 --catalog riak --schema t
use riak.t;
select * from logs;
select * from logs l, users u where l.accessor = u.id;
```

**Comment by fire** [comment]
I am still getting com.facebook.presto.spi.PrestoException: No nodes available to run query on my vagrant setup. I was able to run using the rp environment, but that isn't ideal.

**Comment by kuenishi** [comment]
Looks like you're not having 1:1 correspond between presto workers and riak nodes? That'll make sense.

**Comment by fire** [comment]
If I set https://github.com/kuenishi/presto-riak/blob/master/src/main/java/com/basho/riak/presto/CoverageSplit.java#L110 to false, my queries work but as your other comment said, it remove locality of riak nodes. What should I do?

I'm assuming there will be 1 coordinator and several presto workers and a riak cluster.
